apiVersion: v1
kind: Service
metadata:
  name: go-rest-api-app-service
  labels:
    app: go-rest-api-app
spec:
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: go-rest-api-app
  type: ClusterIP
